const figuresDataset = [
  {
    "id": "makise",
    "title": "ドリームテック シュタインズ・ゲート 牧瀬紅莉栖 白衣style",
    "img": "149.jpg",
    "brand": "WAVE",
    "featured": true,
    "folder": "makise",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "altersora",
    "title": "春日野 穹 Ending Ver.",
    "img": "139.jpg",
    "brand": "ALTER",
    "featured": true,
    "folder": "altersora",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "gokusinsukasi01",
    "title": "濁心スカジ",
    "img": "138.jpg",
    "brand": "MYETHOS",
    "featured": true,
    "folder": "gokusinsukasi01",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "furanndo",
    "title": "フランドール・スカーレット",
    "img": "133.jpg",
    "brand": "ALTER",
    "featured": true,
    "folder": "furanndo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "PA15",
    "title": "PA-15 高校心動物語",
    "img": "131.jpg",
    "brand": "GSC",
    "featured": true,
    "folder": "PA15",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "yodayo",
    "title": "百鬼あやめ",
    "img": "130.jpg",
    "brand": "KOTOBUKIYA",
    "featured": true,
    "folder": "yodayo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Ryza",
    "title": "ライザリン・シュタウト",
    "img": "125.jpg",
    "brand": "GSC",
    "featured": true,
    "folder": "Ryza",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "hokusai1",
    "title": "セイバー/葛飾北斎",
    "img": "124.jpg",
    "brand": "GSC",
    "featured": true,
    "folder": "hokusai1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Javelin1",
    "title": "ジャベリン ビーチピクニック！Ver.",
    "img": "121.jpg",
    "brand": "ALTER",
    "featured": true,
    "folder": "Javelin1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "iriasu1",
    "title": "イリヤスフィール・フォン・アインツベルン PRISMA Racing ver.",
    "img": "120.jpg",
    "brand": "STRONGER",
    "featured": true,
    "folder": "iriasu1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "YingSwei1",
    "title": "応瑞",
    "img": "119.jpg",
    "brand": "NEONMAX",
    "featured": true,
    "folder": "YingSwei1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "fuyuko",
    "title": "黛冬優子 Neon Light Romancer Ver.",
    "img": "140.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "fuyuko",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "miku5th",
    "title": "初音ミクシンフォニー 5th Anniversary Ver.",
    "img": "128.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "miku5th",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "ginkohareki",
    "title": "空銀子 和服Ver.",
    "img": "126.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "ginkohareki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "furanndoru",
    "title": "フランドール・スカーレット [AQ]",
    "img": "99.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "furanndoru",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "mikudress",
    "title": "初音未來 Memorial Dress Ver.",
    "img": "94.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "mikudress",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "BEATLESS_full",
    "title": "レイシア 2018 <BLACK MONOLITH>展開Ver.",
    "img": "15.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "BEATLESS full",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "chocola",
    "title": "POP UP PARADE 巧克力",
    "img": "85.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "chocola",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "vanilla",
    "title": "POP UP PARADE 香草",
    "img": "86.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "vanilla",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "shutenndouji",
    "title": "アサシン/酒呑童子",
    "img": "44.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "shutenndouji",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "okitasouji",
    "title": "セイバー/沖田総司",
    "img": "43.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "okitasouji",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "nero",
    "title": "アイドル皇帝/ネロ",
    "img": "49.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "nero",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "white",
    "title": "ノーゲーム・ノーライフ 白",
    "img": "03.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "white",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "canncole",
    "title": "愛宕 重兵裝Ver.& 高雄 重兵裝Ver.",
    "img": "32.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "canncole",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "takao",
    "title": "高雄 重兵裝Ver.",
    "img": "34.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "takao",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "adago",
    "title": "愛宕 重兵裝Ver.",
    "img": "33.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "adago",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_alter_huke",
    "title": "セイバー・オルタ huke コラボパッケージ",
    "img": "24.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "saber alter huke",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "racing_miku_sepang",
    "title": "レーシングミク 2015 Ver.",
    "img": "71.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "racing miku sepang",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "miku_race",
    "title": "レーシングミク セパンVer.",
    "img": "50.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "miku race",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "eriri",
    "title": "澤村・スペンサー・英梨々",
    "img": "48.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "eriri",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sieru",
    "title": "シエル・アランソン",
    "img": "30.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "sieru",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "masasekurisu",
    "title": "牧瀬紅莉栖 白衣Ver.",
    "img": "46.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "masasekurisu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sinobu",
    "title": "忍野忍",
    "img": "31.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "sinobu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "BGS",
    "title": "ブラックゴールドソー -animation version-",
    "img": "27.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "BGS",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "DM",
    "title": "デッドマスター -animation version-",
    "img": "28.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "DM",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "caster",
    "title": "キャスター [Fate/EXTRA]",
    "img": "70.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "caster",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "senngoku",
    "title": "千石撫子",
    "img": "57.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "senngoku",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber",
    "title": "セイバー ～約束された勝利の劍(エクスカリバー)～",
    "img": "42.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "saber",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_lily",
    "title": "セイバー・リリィ ～全て遠き理想鄉(アヴァロン)～",
    "img": "41.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "saber lily",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "datumaki",
    "title": "戦慄のタツマキ",
    "img": "143.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "datumaki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "pora",
    "title": "ポーラ 水辺のハプニング？Ver.",
    "img": "142.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "pora",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "alterraiza1",
    "title": "ライザ（ライザリン・シュタウト）",
    "img": "132.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "alterraiza1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "miyamotofure1",
    "title": "宮本 フレデリカ フレ・慢·拉·模樣Ver.",
    "img": "129.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "miyamotofure1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Baltimorewhite",
    "title": "ボルチモア",
    "img": "123.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "Baltimorewhite",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "GrafZeppelin",
    "title": "グラーフ・ツェッペリン 砂浜のウルズVer.",
    "img": "118.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "GrafZeppelin",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "siriasu1",
    "title": "シリアス 青雲映す碧波Ver.",
    "img": "112.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "siriasu1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "miyamoto1",
    "title": "バーサーカー／宮本 武蔵",
    "img": "113.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "miyamoto1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rutorionfan1",
    "title": "ル・トリオンファン",
    "img": "110.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "rutorionfan1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "lala1",
    "title": "ララ・サタリン・デビルーク 水着Ver.",
    "img": "107.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "lala1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sofi1",
    "title": "ソフィー（ソフィー・ノイエンミュラー）",
    "img": "105.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "sofi1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "ginko",
    "title": "空 銀子 猫耳姉弟子Ver.",
    "img": "103.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "ginko",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "shokuhoumisaki",
    "title": "食蜂操祈",
    "img": "97.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "shokuhoumisaki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sentoruisu",
    "title": "セント路易斯 (St. Louis)",
    "img": "96.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "sentoruisu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "momo",
    "title": "モモ・ベリア・デビルーク -ベビードール Ver.-",
    "img": "39.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "momo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_alter_mizuki",
    "title": "ライダー／アルトリア・ペンドラゴン［オルタ］",
    "img": "16.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "saber alter mizuki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Jeanne",
    "title": "アヴェンジャー／ジャンヌ・ダルク［オルタ］",
    "img": "92.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "Jeanne",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "hayami_kanade",
    "title": "速水 奏 ミスティック・ドーンVer.",
    "img": "10.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "hayami kanade",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "yami",
    "title": "金色的闇 ナースVer.",
    "img": "20.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "yami",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "purafuta",
    "title": "プラフタ",
    "img": "21.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "purafuta",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sekasaha",
    "title": "スカサハ 部屋着モード",
    "img": "19.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "sekasaha",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rannco",
    "title": "神崎 蘭子 薔薇の闇姫Ver.",
    "img": "29.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "rannco",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_alter_dress",
    "title": "セイバー／アルトリア・ペンドラゴン［オルタ］ ドレスVer.",
    "img": "25.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "saber alter dress",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sora",
    "title": "春日野 穹 チャインドレスVer.",
    "img": "37.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "sora",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "baochai1",
    "title": "バオ・チャイ",
    "img": "111.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "baochai1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Dai_Yu",
    "title": "Dai-Yu ダイ・ユー",
    "img": "77.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "Dai-Yu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Chun_Mei",
    "title": "春梅 Chun-Mei",
    "img": "75.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "Chun-Mei",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Jin_Lian",
    "title": "金蓮 Jin-Lian 常套式Ver.",
    "img": "73.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "Jin-Lian",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "JinLian",
    "title": "金蓮 Jin-Lian",
    "img": "74.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "JinLian",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Ping_Yi",
    "title": "瓶兒 Ping-Yi",
    "img": "76.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "Ping-Yi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "chie",
    "title": "少女のトゲ ちえ",
    "img": "93.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "chie",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "himari",
    "title": "「お嬢様の花園」天竺葵",
    "img": "81.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "himari",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "swan",
    "title": "白のオデット＆黒のオディール",
    "img": "01.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "swan",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "swan_b",
    "title": "黑 of オディール",
    "img": "04.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "swan b",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "swan_w",
    "title": "白 of オデット",
    "img": "05.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "swan w",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sannsi",
    "title": "三世村正 ナースver.",
    "img": "80.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "sannsi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "fuyutsukiwaring",
    "title": "冬月茉莉 純白ver.",
    "img": "69.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "fuyutsukiwaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saekiaiwaring",
    "title": "フォルト!! A 佐伯藍",
    "img": "68.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "saekiaiwaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "mimayawaring",
    "title": "神和住 真夜テニスウェアver.",
    "img": "90.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "mimayawaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "natuki",
    "title": "「ブリリアント・サマー」夏樹沙耶",
    "img": "89.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "natuki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "noeru",
    "title": "「聖夜の贈りもの」 ノエル・シャ・ノワール",
    "img": "45.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "noeru",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rakuenn",
    "title": "「楽園の乙女」スージー・サン",
    "img": "78.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "rakuenn",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sioubi",
    "title": "「お嬢様のいたずら」鐘火八重",
    "img": "79.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "sioubi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "himegamiwaring",
    "title": "「最果ての白雪姫」姫神六花",
    "img": "88.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "himegamiwaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "nanakusa",
    "title": "よふかしのうた 七草ナズナ",
    "img": "147.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "nanakusa",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sionn",
    "title": "紫咲シオン",
    "img": "137.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "sionn",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sennto",
    "title": "セントー (Centaur)",
    "img": "22.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "sennto",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "anaberu2",
    "title": "紫陽花的妖精 アナベル",
    "img": "66.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "anaberu2",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "dasiy2",
    "title": "雛菊の妖精 デイジー",
    "img": "65.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "dasiy2",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "aizu",
    "title": "アイズ・ヴァレンシュタイン",
    "img": "40.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "aizu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "riine",
    "title": "電脳妖精アイオーン・リーネ",
    "img": "63.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "riine",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "irohahime",
    "title": "五郎八姫 Tony Ver.",
    "img": "58.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "irohahime",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "forute",
    "title": "ディアドラグーン・フォルテ",
    "img": "35.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "forute",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "feari",
    "title": "Tony'sヒロインコレクション フリージア",
    "img": "62.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "feari",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sakuya",
    "title": "光明的熾天使サクヤ -Mode：セラフィム-",
    "img": "56.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "sakuya",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "anaberu",
    "title": "Tony'sヒロインコレクション アナベル",
    "img": "61.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "anaberu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "maria",
    "title": "キルマリア・アイディーン",
    "img": "51.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "maria",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "oliwie",
    "title": "ダークエンジェル・オリヴィエ",
    "img": "36.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "oliwie",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "daisy",
    "title": "デイジー",
    "img": "60.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "daisy",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "panisu",
    "title": "パニス・アンジェリクス",
    "img": "54.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "panisu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kuroyuki",
    "title": "アクセル・ワールド 黑雪姫",
    "img": "52.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "kuroyuki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "yui",
    "title": "篁唯依 -月華-",
    "img": "53.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "yui",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kureha",
    "title": "吳羽冬華-クレハ",
    "img": "55.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "kureha",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kouhiw01",
    "title": "ARMS NOTE 水泳部のコウ快ちゃん white",
    "img": "134.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "kouhiw01",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kasima03",
    "title": "鹿島 輕裝ver",
    "img": "136.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "kasima03",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "itsusiki",
    "title": "一色いろは",
    "img": "135.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "itsusiki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kouhi",
    "title": "ARMS NOTE 水泳部のコウハイちゃん",
    "img": "84.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "kouhi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "pride",
    "title": "七つの大罪 魔王黙示録 傲慢ノ章 ルシファー -スイカ割りノ節- 金色ノ項 通常版",
    "img": "82.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "pride",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kurumisitagi",
    "title": "時崎狂三 ランジェリーVer",
    "img": "83.jpg",
    "brand": "ALPHAMAX",
    "featured": false,
    "folder": "kurumisitagi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rennga",
    "title": "愛玩妖精 蓮華",
    "img": "64.jpg",
    "brand": "ALPHAMAX",
    "featured": false,
    "folder": "rennga",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kurumi_tokei",
    "title": "時崎狂三",
    "img": "38.jpg",
    "brand": "ALPHAMAX",
    "featured": false,
    "folder": "kurumi tokei",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sakuya_waio",
    "title": "シャイニング・アーク サクヤ -Mode:ヴァイオレット-",
    "img": "72.jpg",
    "brand": "ALPHAMAX",
    "featured": false,
    "folder": "sakuya waio",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "marugarete4w",
    "title": "マルガレーテ",
    "img": "127.jpg",
    "brand": "NATIVE",
    "featured": false,
    "folder": "marugarete4w",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "youseiqueen",
    "title": "Dai-Yu ダイ・ユー (Native)",
    "img": "87.jpg",
    "brand": "NATIVE",
    "featured": false,
    "folder": "youseiqueen",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "alicewaring",
    "title": "アリス of 品評會",
    "img": "02.jpg",
    "brand": "NATIVE",
    "featured": false,
    "folder": "alicewaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "arikowaring",
    "title": "夜伽の国の亞璃子",
    "img": "91.jpg",
    "brand": "NATIVE",
    "featured": false,
    "folder": "arikowaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Ahri",
    "title": "Myethos-英雄聯盟 靈魂蓮華 阿璃",
    "img": "152.jpg",
    "brand": "MYETHOS",
    "featured": false,
    "folder": "Ahri",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "AZD",
    "title": "A-Z:[D]",
    "img": "102.jpg",
    "brand": "MYETHOS",
    "featured": false,
    "folder": "AZD",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "hakuchou1",
    "title": "ドリームテック 白鳥の女の子",
    "img": "100.jpg",
    "brand": "WAVE",
    "featured": false,
    "folder": "hakuchou1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "allsunday",
    "title": "Playback Memories” ミス・オールサンデー",
    "img": "151.jpg",
    "brand": "MEGAHOUSE",
    "featured": false,
    "folder": "allsunday",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "habbkoku",
    "title": "ワンピース ボア・ハンコック Ver.BB",
    "img": "145.jpg",
    "brand": "MEGAHOUSE",
    "featured": false,
    "folder": "habbkoku",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "makima",
    "title": "BiCute Bunnies Figure チェンソーマン ーマキマー",
    "img": "154.jpg",
    "brand": "FURYU",
    "featured": false,
    "folder": "makima",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "pawa",
    "title": "BiCute Bunnies Figure チェンソーマン ーパワーー",
    "img": "153.jpg",
    "brand": "FURYU",
    "featured": false,
    "folder": "pawa",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "shutenzom1",
    "title": "アサシン／酒呑童子 英霊祭裝Ver.",
    "img": "116.jpg",
    "brand": "QUESQ",
    "featured": false,
    "folder": "shutenzom1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "UCINANA",
    "title": "ToLOVEる－とらぶる－ダークネス ナナ・アスタ・デビルーク ダークネス",
    "img": "101.jpg",
    "brand": "UCI",
    "featured": false,
    "folder": "UCINANA",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Astolfo",
    "title": "ジャンヌ・ダルク＆アストルフォ TYPE-MOON Racing ver.",
    "img": "98.jpg",
    "brand": "PLUSONE",
    "featured": false,
    "folder": "Astolfo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "mikusakura",
    "title": "櫻未來～桜妖精ver",
    "img": "95.jpg",
    "brand": "SPIRITALE",
    "featured": false,
    "folder": "mikusakura",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "amilia_black",
    "title": "エミリア -Crystal Dress Ver-",
    "img": "12.jpg",
    "brand": "ESTREAM",
    "featured": false,
    "folder": "amilia black",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rinsia",
    "title": "第3村人 リンシア",
    "img": "18.jpg",
    "brand": "VERTEX",
    "featured": false,
    "folder": "rinsia",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Albedo",
    "title": "オーバーロード アルベド",
    "img": "67.jpg",
    "brand": "FNEX",
    "featured": false,
    "folder": "Albedo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_alter_kimono",
    "title": "セイバーオルタ 着物Ver.",
    "img": "11.jpg",
    "brand": "KADOKAWA",
    "featured": false,
    "folder": "saber alter kimono",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_haregi",
    "title": "saber 晴れ着",
    "img": "23.jpg",
    "brand": "ANIPLEX",
    "featured": false,
    "folder": "saber haregi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sie1",
    "title": "美咲詩絵 「夏草」",
    "img": "108.jpg",
    "brand": "DAIKI",
    "featured": false,
    "folder": "sie1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kurumi",
    "title": "デート・ア・ライブⅡ「時崎 狂三」",
    "img": "09.jpg",
    "brand": "BROCCOLI",
    "featured": false,
    "folder": "kurumi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "arisa",
    "title": "アリサ・イリーニチナ・アミエーラ",
    "img": "47.jpg",
    "brand": "PLUM",
    "featured": false,
    "folder": "arisa",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sakuya_teacher",
    "title": "サクヤ -女教師Ver.-",
    "img": "59.jpg",
    "brand": "FLARE",
    "featured": false,
    "folder": "sakuya teacher",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "nejire",
    "title": "波動ねじれ ヒーロースーツ",
    "img": "148.jpg",
    "brand": "BELLFINE",
    "featured": false,
    "folder": "nejire",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sigure",
    "title": "時雨羽衣 しぐれうい",
    "img": "141.jpg",
    "brand": "POP",
    "featured": false,
    "folder": "sigure",
    "totalFrames": 36,
    "customUrl": "",
    "reviewLink": "",
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Hancock",
    "title": "Maximum 波雅·漢考克",
    "img": "144.jpg",
    "brand": "FNEX",
    "featured": false,
    "folder": "Hancock",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "15th",
    "title": "Lemoe Vtuber 瀕臨絕種團 No.Fifteen 十五號",
    "img": "155.jpg",
    "brand": "LEMOE",
    "featured": false,
    "folder": "15th_up",
    "totalFrames": 33,
    "customUrl": "",
    "reviewLink": "",
    "credit": "由巴哈網友 <span class='text-violet-400'>998</span> 提供",
    "is18Plus": false,
    "modes": [
      {
        "name": "通常角度",
        "folder": "15th",
        "totalFrames": 33,
        "is18Plus": false
      },
      {
        "name": "低角度仰視",
        "folder": "15th",
        "totalFrames": 33,
        "is18Plus": false
      }
    ]
  },
  {
    "id": "miraboreasu1",
    "title": "黑龍 - ミラボレアス",
    "img": "109.jpg",
    "brand": "CBF",
    "featured": false,
    "folder": "miraboreasu1",
    "totalFrames": 36,
    "customUrl": "",
    "reviewLink": "https://你的開箱文網址.com",
    "credit": "由巴哈網友 <span class='text-red-400'>阿孟</span> 提供",
    "is18Plus": false,
    "modes": [
      {
        "name": "全彩",
        "folder": "miraboreasu1",
        "totalFrames": 36,
        "is18Plus": false
      },
      {
        "name": "半彩",
        "folder": "miraboreasu2",
        "totalFrames": 36,
        "is18Plus": false
      },
      {
        "name": "77",
        "folder": "miraboreasu3",
        "totalFrames": 36,
        "is18Plus": false
      },
      {
        "name": "88",
        "folder": "miraboreasu4",
        "totalFrames": 36,
        "is18Plus": true
      }
    ]
  },
  {
    "id": "Xayah",
    "title": "英雄聯盟 剎雅",
    "img": "150.jpg",
    "brand": "HOBBYMAX",
    "featured": false,
    "folder": "Xayah",
    "totalFrames": 36,
    "customUrl": "http:\\\\google.com",
    "reviewLink": "",
    "credit": "由巴哈網友 <span class='text-blue-400'>88</span> 提供",
    "is18Plus": false,
    "modes": null
  }
];