const figuresDataset = [
  {
    "id": "667788",
    "title": "\u65B0\u6A21\u578B1",
    "brand": "GSC",
    "folder": "667788",
    "totalFrames": 36,
    "featured": false,
    "is18Plus": false,
    "img": "1.jpg"
  },
  {
    "id": "7788",
    "title": "\u521D\u56E0",
    "brand": "GSC",
    "folder": "7788",
    "totalFrames": 30,
    "featured": false,
    "is18Plus": false,
    "credit": "\u7531\u5DF4\u54C8\u7DB2\u53CB \u003Cspan class=\u0027text-red-400\u0027\u003E\u963F\u5B5F\u003C/span\u003E \u63D0\u4F9B",
    "img": "33.JPG"
  },
  {
    "id": "makise",
    "title": "\u30C9\u30EA\u30FC\u30E0\u30C6\u30C3\u30AF \u30B7\u30E5\u30BF\u30A4\u30F3\u30BA\u30FB\u30B2\u30FC\u30C8 \u7267\u702C\u7D05\u8389\u6816 \u767D\u8863style",
    "img": "149.jpg",
    "brand": "WAVE",
    "featured": true,
    "folder": "makise",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "altersora",
    "title": "\u6625\u65E5\u91CE \u7A79 Ending Ver.",
    "img": "139.jpg",
    "brand": "ALTER",
    "featured": true,
    "folder": "altersora",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "gokusinsukasi01",
    "title": "\u6FC1\u5FC3\u30B9\u30AB\u30B8",
    "img": "138.jpg",
    "brand": "MYETHOS",
    "featured": true,
    "folder": "gokusinsukasi01",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "furanndo",
    "title": "\u30D5\u30E9\u30F3\u30C9\u30FC\u30EB\u30FB\u30B9\u30AB\u30FC\u30EC\u30C3\u30C8",
    "img": "133.jpg",
    "brand": "ALTER",
    "featured": true,
    "folder": "furanndo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "PA15",
    "title": "PA-15 \u9AD8\u6821\u5FC3\u52D5\u7269\u8A9E",
    "img": "131.jpg",
    "brand": "GSC",
    "featured": true,
    "folder": "PA15",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "yodayo",
    "title": "\u767E\u9B3C\u3042\u3084\u3081",
    "img": "130.jpg",
    "brand": "KOTOBUKIYA",
    "featured": true,
    "folder": "yodayo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Ryza",
    "title": "\u30E9\u30A4\u30B6\u30EA\u30F3\u30FB\u30B7\u30E5\u30BF\u30A6\u30C8",
    "img": "125.jpg",
    "brand": "GSC",
    "featured": true,
    "folder": "Ryza",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "hokusai1",
    "title": "\u30BB\u30A4\u30D0\u30FC/\u845B\u98FE\u5317\u658E",
    "img": "124.jpg",
    "brand": "GSC",
    "featured": true,
    "folder": "hokusai1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Javelin1",
    "title": "\u30B8\u30E3\u30D9\u30EA\u30F3 \u30D3\u30FC\u30C1\u30D4\u30AF\u30CB\u30C3\u30AF\uFF01Ver.",
    "img": "121.jpg",
    "brand": "ALTER",
    "featured": true,
    "folder": "Javelin1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "iriasu1",
    "title": "\u30A4\u30EA\u30E4\u30B9\u30D5\u30A3\u30FC\u30EB\u30FB\u30D5\u30A9\u30F3\u30FB\u30A2\u30A4\u30F3\u30C4\u30D9\u30EB\u30F3 PRISMA Racing ver.",
    "img": "120.jpg",
    "brand": "STRONGER",
    "featured": true,
    "folder": "iriasu1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "YingSwei1",
    "title": "\u5FDC\u745E",
    "img": "119.jpg",
    "brand": "NEONMAX",
    "featured": true,
    "folder": "YingSwei1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "fuyuko",
    "title": "\u9EDB\u51AC\u512A\u5B50 Neon Light Romancer Ver.",
    "img": "140.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "fuyuko",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "miku5th",
    "title": "\u521D\u97F3\u30DF\u30AF\u30B7\u30F3\u30D5\u30A9\u30CB\u30FC 5th Anniversary Ver.",
    "img": "128.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "miku5th",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "ginkohareki",
    "title": "\u7A7A\u9280\u5B50 \u548C\u670DVer.",
    "img": "126.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "ginkohareki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "furanndoru",
    "title": "\u30D5\u30E9\u30F3\u30C9\u30FC\u30EB\u30FB\u30B9\u30AB\u30FC\u30EC\u30C3\u30C8 [AQ]",
    "img": "99.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "furanndoru",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "mikudress",
    "title": "\u521D\u97F3\u672A\u4F86 Memorial Dress Ver.",
    "img": "94.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "mikudress",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "BEATLESS_full",
    "title": "\u30EC\u30A4\u30B7\u30A2 2018 \u003CBLACK MONOLITH\u003E\u5C55\u958BVer.",
    "img": "15.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "BEATLESS full",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "chocola",
    "title": "POP UP PARADE \u5DE7\u514B\u529B",
    "img": "85.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "chocola",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "vanilla",
    "title": "POP UP PARADE \u9999\u8349",
    "img": "86.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "vanilla",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "shutenndouji",
    "title": "\u30A2\u30B5\u30B7\u30F3/\u9152\u5451\u7AE5\u5B50",
    "img": "44.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "shutenndouji",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "okitasouji",
    "title": "\u30BB\u30A4\u30D0\u30FC/\u6C96\u7530\u7DCF\u53F8",
    "img": "43.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "okitasouji",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "nero",
    "title": "\u30A2\u30A4\u30C9\u30EB\u7687\u5E1D/\u30CD\u30ED",
    "img": "49.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "nero",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "white",
    "title": "\u30CE\u30FC\u30B2\u30FC\u30E0\u30FB\u30CE\u30FC\u30E9\u30A4\u30D5 \u767D",
    "img": "03.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "white",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "canncole",
    "title": "\u611B\u5B95 \u91CD\u5175\u88DDVer.\u0026 \u9AD8\u96C4 \u91CD\u5175\u88DDVer.",
    "img": "32.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "canncole",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "takao",
    "title": "\u9AD8\u96C4 \u91CD\u5175\u88DDVer.",
    "img": "34.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "takao",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "adago",
    "title": "\u611B\u5B95 \u91CD\u5175\u88DDVer.",
    "img": "33.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "adago",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_alter_huke",
    "title": "\u30BB\u30A4\u30D0\u30FC\u30FB\u30AA\u30EB\u30BF huke \u30B3\u30E9\u30DC\u30D1\u30C3\u30B1\u30FC\u30B8",
    "img": "24.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "saber alter huke",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "racing_miku_sepang",
    "title": "\u30EC\u30FC\u30B7\u30F3\u30B0\u30DF\u30AF 2015 Ver.",
    "img": "71.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "racing miku sepang",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "miku_race",
    "title": "\u30EC\u30FC\u30B7\u30F3\u30B0\u30DF\u30AF \u30BB\u30D1\u30F3Ver.",
    "img": "50.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "miku race",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "eriri",
    "title": "\u6FA4\u6751\u30FB\u30B9\u30DA\u30F3\u30B5\u30FC\u30FB\u82F1\u68A8\u3005",
    "img": "48.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "eriri",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sieru",
    "title": "\u30B7\u30A8\u30EB\u30FB\u30A2\u30E9\u30F3\u30BD\u30F3",
    "img": "30.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "sieru",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "masasekurisu",
    "title": "\u7267\u702C\u7D05\u8389\u6816 \u767D\u8863Ver.",
    "img": "46.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "masasekurisu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sinobu",
    "title": "\u5FCD\u91CE\u5FCD",
    "img": "31.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "sinobu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "BGS",
    "title": "\u30D6\u30E9\u30C3\u30AF\u30B4\u30FC\u30EB\u30C9\u30BD\u30FC -animation version-",
    "img": "27.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "BGS",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "DM",
    "title": "\u30C7\u30C3\u30C9\u30DE\u30B9\u30BF\u30FC -animation version-",
    "img": "28.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "DM",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "caster",
    "title": "\u30AD\u30E3\u30B9\u30BF\u30FC [Fate/EXTRA]",
    "img": "70.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "caster",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "senngoku",
    "title": "\u5343\u77F3\u64AB\u5B50",
    "img": "57.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "senngoku",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber",
    "title": "\u30BB\u30A4\u30D0\u30FC \uFF5E\u7D04\u675F\u3055\u308C\u305F\u52DD\u5229\u306E\u528D(\u30A8\u30AF\u30B9\u30AB\u30EA\u30D0\u30FC)\uFF5E",
    "img": "42.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "saber",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_lily",
    "title": "\u30BB\u30A4\u30D0\u30FC\u30FB\u30EA\u30EA\u30A3 \uFF5E\u5168\u3066\u9060\u304D\u7406\u60F3\u9109(\u30A2\u30F4\u30A1\u30ED\u30F3)\uFF5E",
    "img": "41.jpg",
    "brand": "GSC",
    "featured": false,
    "folder": "saber lily",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "datumaki",
    "title": "\u6226\u6144\u306E\u30BF\u30C4\u30DE\u30AD",
    "img": "143.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "datumaki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "pora",
    "title": "\u30DD\u30FC\u30E9 \u6C34\u8FBA\u306E\u30CF\u30D7\u30CB\u30F3\u30B0\uFF1FVer.",
    "img": "142.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "pora",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "alterraiza1",
    "title": "\u30E9\u30A4\u30B6\uFF08\u30E9\u30A4\u30B6\u30EA\u30F3\u30FB\u30B7\u30E5\u30BF\u30A6\u30C8\uFF09",
    "img": "132.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "alterraiza1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "miyamotofure1",
    "title": "\u5BAE\u672C \u30D5\u30EC\u30C7\u30EA\u30AB \u30D5\u30EC\u30FB\u6162\u00B7\u62C9\u00B7\u6A21\u6A23Ver.",
    "img": "129.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "miyamotofure1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Baltimorewhite",
    "title": "\u30DC\u30EB\u30C1\u30E2\u30A2",
    "img": "123.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "Baltimorewhite",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "GrafZeppelin",
    "title": "\u30B0\u30E9\u30FC\u30D5\u30FB\u30C4\u30A7\u30C3\u30DA\u30EA\u30F3 \u7802\u6D5C\u306E\u30A6\u30EB\u30BAVer.",
    "img": "118.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "GrafZeppelin",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "siriasu1",
    "title": "\u30B7\u30EA\u30A2\u30B9 \u9752\u96F2\u6620\u3059\u78A7\u6CE2Ver.",
    "img": "112.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "siriasu1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "miyamoto1",
    "title": "\u30D0\u30FC\u30B5\u30FC\u30AB\u30FC\uFF0F\u5BAE\u672C \u6B66\u8535",
    "img": "113.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "miyamoto1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rutorionfan1",
    "title": "\u30EB\u30FB\u30C8\u30EA\u30AA\u30F3\u30D5\u30A1\u30F3",
    "img": "110.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "rutorionfan1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "lala1",
    "title": "\u30E9\u30E9\u30FB\u30B5\u30BF\u30EA\u30F3\u30FB\u30C7\u30D3\u30EB\u30FC\u30AF \u6C34\u7740Ver.",
    "img": "107.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "lala1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sofi1",
    "title": "\u30BD\u30D5\u30A3\u30FC\uFF08\u30BD\u30D5\u30A3\u30FC\u30FB\u30CE\u30A4\u30A8\u30F3\u30DF\u30E5\u30E9\u30FC\uFF09",
    "img": "105.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "sofi1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "ginko",
    "title": "\u7A7A \u9280\u5B50 \u732B\u8033\u59C9\u5F1F\u5B50Ver.",
    "img": "103.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "ginko",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "shokuhoumisaki",
    "title": "\u98DF\u8702\u64CD\u7948",
    "img": "97.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "shokuhoumisaki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sentoruisu",
    "title": "\u30BB\u30F3\u30C8\u8DEF\u6613\u65AF (St. Louis)",
    "img": "96.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "sentoruisu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "momo",
    "title": "\u30E2\u30E2\u30FB\u30D9\u30EA\u30A2\u30FB\u30C7\u30D3\u30EB\u30FC\u30AF -\u30D9\u30D3\u30FC\u30C9\u30FC\u30EB Ver.-",
    "img": "39.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "momo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_alter_mizuki",
    "title": "\u30E9\u30A4\u30C0\u30FC\uFF0F\u30A2\u30EB\u30C8\u30EA\u30A2\u30FB\u30DA\u30F3\u30C9\u30E9\u30B4\u30F3\uFF3B\u30AA\u30EB\u30BF\uFF3D",
    "img": "16.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "saber alter mizuki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Jeanne",
    "title": "\u30A2\u30F4\u30A7\u30F3\u30B8\u30E3\u30FC\uFF0F\u30B8\u30E3\u30F3\u30CC\u30FB\u30C0\u30EB\u30AF\uFF3B\u30AA\u30EB\u30BF\uFF3D",
    "img": "92.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "Jeanne",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "hayami_kanade",
    "title": "\u901F\u6C34 \u594F \u30DF\u30B9\u30C6\u30A3\u30C3\u30AF\u30FB\u30C9\u30FC\u30F3Ver.",
    "img": "10.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "hayami kanade",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "yami",
    "title": "\u91D1\u8272\u7684\u95C7 \u30CA\u30FC\u30B9Ver.",
    "img": "20.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "yami",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "purafuta",
    "title": "\u30D7\u30E9\u30D5\u30BF",
    "img": "21.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "purafuta",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sekasaha",
    "title": "\u30B9\u30AB\u30B5\u30CF \u90E8\u5C4B\u7740\u30E2\u30FC\u30C9",
    "img": "19.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "sekasaha",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rannco",
    "title": "\u795E\u5D0E \u862D\u5B50 \u8594\u8587\u306E\u95C7\u59EBVer.",
    "img": "29.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "rannco",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_alter_dress",
    "title": "\u30BB\u30A4\u30D0\u30FC\uFF0F\u30A2\u30EB\u30C8\u30EA\u30A2\u30FB\u30DA\u30F3\u30C9\u30E9\u30B4\u30F3\uFF3B\u30AA\u30EB\u30BF\uFF3D \u30C9\u30EC\u30B9Ver.",
    "img": "25.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "saber alter dress",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sora",
    "title": "\u6625\u65E5\u91CE \u7A79 \u30C1\u30E3\u30A4\u30F3\u30C9\u30EC\u30B9Ver.",
    "img": "37.jpg",
    "brand": "ALTER",
    "featured": false,
    "folder": "sora",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "baochai1",
    "title": "\u30D0\u30AA\u30FB\u30C1\u30E3\u30A4",
    "img": "111.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "baochai1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Dai_Yu",
    "title": "Dai-Yu \u30C0\u30A4\u30FB\u30E6\u30FC",
    "img": "77.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "Dai-Yu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Chun_Mei",
    "title": "\u6625\u6885 Chun-Mei",
    "img": "75.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "Chun-Mei",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Jin_Lian",
    "title": "\u91D1\u84EE Jin-Lian \u5E38\u5957\u5F0FVer.",
    "img": "73.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "Jin-Lian",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "JinLian",
    "title": "\u91D1\u84EE Jin-Lian",
    "img": "74.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "JinLian",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Ping_Yi",
    "title": "\u74F6\u5152 Ping-Yi",
    "img": "76.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "Ping-Yi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "chie",
    "title": "\u5C11\u5973\u306E\u30C8\u30B2 \u3061\u3048",
    "img": "93.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "chie",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "himari",
    "title": "\u300C\u304A\u5B22\u69D8\u306E\u82B1\u5712\u300D\u5929\u7AFA\u8475",
    "img": "81.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "himari",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "swan",
    "title": "\u767D\u306E\u30AA\u30C7\u30C3\u30C8\uFF06\u9ED2\u306E\u30AA\u30C7\u30A3\u30FC\u30EB",
    "img": "01.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "swan",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "swan_b",
    "title": "\u9ED1 of \u30AA\u30C7\u30A3\u30FC\u30EB",
    "img": "04.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "swan b",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "swan_w",
    "title": "\u767D of \u30AA\u30C7\u30C3\u30C8",
    "img": "05.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "swan w",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sannsi",
    "title": "\u4E09\u4E16\u6751\u6B63 \u30CA\u30FC\u30B9ver.",
    "img": "80.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "sannsi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "fuyutsukiwaring",
    "title": "\u51AC\u6708\u8309\u8389 \u7D14\u767Dver.",
    "img": "69.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "fuyutsukiwaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saekiaiwaring",
    "title": "\u30D5\u30A9\u30EB\u30C8!! A \u4F50\u4F2F\u85CD",
    "img": "68.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "saekiaiwaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "mimayawaring",
    "title": "\u795E\u548C\u4F4F \u771F\u591C\u30C6\u30CB\u30B9\u30A6\u30A7\u30A2ver.",
    "img": "90.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "mimayawaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "natuki",
    "title": "\u300C\u30D6\u30EA\u30EA\u30A2\u30F3\u30C8\u30FB\u30B5\u30DE\u30FC\u300D\u590F\u6A39\u6C99\u8036",
    "img": "89.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "natuki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "noeru",
    "title": "\u300C\u8056\u591C\u306E\u8D08\u308A\u3082\u306E\u300D \u30CE\u30A8\u30EB\u30FB\u30B7\u30E3\u30FB\u30CE\u30EF\u30FC\u30EB",
    "img": "45.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "noeru",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rakuenn",
    "title": "\u300C\u697D\u5712\u306E\u4E59\u5973\u300D\u30B9\u30FC\u30B8\u30FC\u30FB\u30B5\u30F3",
    "img": "78.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "rakuenn",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sioubi",
    "title": "\u300C\u304A\u5B22\u69D8\u306E\u3044\u305F\u305A\u3089\u300D\u9418\u706B\u516B\u91CD",
    "img": "79.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "sioubi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "himegamiwaring",
    "title": "\u300C\u6700\u679C\u3066\u306E\u767D\u96EA\u59EB\u300D\u59EB\u795E\u516D\u82B1",
    "img": "88.jpg",
    "brand": "SKYTUBE",
    "featured": false,
    "folder": "himegamiwaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "nanakusa",
    "title": "\u3088\u3075\u304B\u3057\u306E\u3046\u305F \u4E03\u8349\u30CA\u30BA\u30CA",
    "img": "147.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "nanakusa",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sionn",
    "title": "\u7D2B\u54B2\u30B7\u30AA\u30F3",
    "img": "137.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "sionn",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sennto",
    "title": "\u30BB\u30F3\u30C8\u30FC (Centaur)",
    "img": "22.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "sennto",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "anaberu2",
    "title": "\u7D2B\u967D\u82B1\u7684\u5996\u7CBE \u30A2\u30CA\u30D9\u30EB",
    "img": "66.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "anaberu2",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "dasiy2",
    "title": "\u96DB\u83CA\u306E\u5996\u7CBE \u30C7\u30A4\u30B8\u30FC",
    "img": "65.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "dasiy2",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "aizu",
    "title": "\u30A2\u30A4\u30BA\u30FB\u30F4\u30A1\u30EC\u30F3\u30B7\u30E5\u30BF\u30A4\u30F3",
    "img": "40.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "aizu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "riine",
    "title": "\u96FB\u8133\u5996\u7CBE\u30A2\u30A4\u30AA\u30FC\u30F3\u30FB\u30EA\u30FC\u30CD",
    "img": "63.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "riine",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "irohahime",
    "title": "\u4E94\u90CE\u516B\u59EB Tony Ver.",
    "img": "58.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "irohahime",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "forute",
    "title": "\u30C7\u30A3\u30A2\u30C9\u30E9\u30B0\u30FC\u30F3\u30FB\u30D5\u30A9\u30EB\u30C6",
    "img": "35.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "forute",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "feari",
    "title": "Tony\u0027s\u30D2\u30ED\u30A4\u30F3\u30B3\u30EC\u30AF\u30B7\u30E7\u30F3 \u30D5\u30EA\u30FC\u30B8\u30A2",
    "img": "62.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "feari",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sakuya",
    "title": "\u5149\u660E\u7684\u71BE\u5929\u4F7F\u30B5\u30AF\u30E4 -Mode\uFF1A\u30BB\u30E9\u30D5\u30A3\u30E0-",
    "img": "56.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "sakuya",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "anaberu",
    "title": "Tony\u0027s\u30D2\u30ED\u30A4\u30F3\u30B3\u30EC\u30AF\u30B7\u30E7\u30F3 \u30A2\u30CA\u30D9\u30EB",
    "img": "61.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "anaberu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "maria",
    "title": "\u30AD\u30EB\u30DE\u30EA\u30A2\u30FB\u30A2\u30A4\u30C7\u30A3\u30FC\u30F3",
    "img": "51.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "maria",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "oliwie",
    "title": "\u30C0\u30FC\u30AF\u30A8\u30F3\u30B8\u30A7\u30EB\u30FB\u30AA\u30EA\u30F4\u30A3\u30A8",
    "img": "36.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "oliwie",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "daisy",
    "title": "\u30C7\u30A4\u30B8\u30FC",
    "img": "60.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "daisy",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "panisu",
    "title": "\u30D1\u30CB\u30B9\u30FB\u30A2\u30F3\u30B8\u30A7\u30EA\u30AF\u30B9",
    "img": "54.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "panisu",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kuroyuki",
    "title": "\u30A2\u30AF\u30BB\u30EB\u30FB\u30EF\u30FC\u30EB\u30C9 \u9ED1\u96EA\u59EB",
    "img": "52.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "kuroyuki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "yui",
    "title": "\u7BC1\u552F\u4F9D -\u6708\u83EF-",
    "img": "53.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "yui",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kureha",
    "title": "\u5433\u7FBD\u51AC\u83EF-\u30AF\u30EC\u30CF",
    "img": "55.jpg",
    "brand": "KOTOBUKIYA",
    "featured": false,
    "folder": "kureha",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kouhiw01",
    "title": "ARMS NOTE \u6C34\u6CF3\u90E8\u306E\u30B3\u30A6\u5FEB\u3061\u3083\u3093 white",
    "img": "134.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "kouhiw01",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kasima03",
    "title": "\u9E7F\u5CF6 \u8F15\u88DDver",
    "img": "136.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "kasima03",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "itsusiki",
    "title": "\u4E00\u8272\u3044\u308D\u306F",
    "img": "135.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "itsusiki",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kouhi",
    "title": "ARMS NOTE \u6C34\u6CF3\u90E8\u306E\u30B3\u30A6\u30CF\u30A4\u3061\u3083\u3093",
    "img": "84.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "kouhi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "pride",
    "title": "\u4E03\u3064\u306E\u5927\u7F6A \u9B54\u738B\u9ED9\u793A\u9332 \u50B2\u6162\u30CE\u7AE0 \u30EB\u30B7\u30D5\u30A1\u30FC -\u30B9\u30A4\u30AB\u5272\u308A\u30CE\u7BC0- \u91D1\u8272\u30CE\u9805 \u901A\u5E38\u7248",
    "img": "82.jpg",
    "brand": "AMAKUNI",
    "featured": false,
    "folder": "pride",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kurumisitagi",
    "title": "\u6642\u5D0E\u72C2\u4E09 \u30E9\u30F3\u30B8\u30A7\u30EA\u30FCVer",
    "img": "83.jpg",
    "brand": "ALPHAMAX",
    "featured": false,
    "folder": "kurumisitagi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rennga",
    "title": "\u611B\u73A9\u5996\u7CBE \u84EE\u83EF",
    "img": "64.jpg",
    "brand": "ALPHAMAX",
    "featured": false,
    "folder": "rennga",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kurumi_tokei",
    "title": "\u6642\u5D0E\u72C2\u4E09",
    "img": "38.jpg",
    "brand": "ALPHAMAX",
    "featured": false,
    "folder": "kurumi tokei",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sakuya_waio",
    "title": "\u30B7\u30E3\u30A4\u30CB\u30F3\u30B0\u30FB\u30A2\u30FC\u30AF \u30B5\u30AF\u30E4 -Mode:\u30F4\u30A1\u30A4\u30AA\u30EC\u30C3\u30C8-",
    "img": "72.jpg",
    "brand": "ALPHAMAX",
    "featured": false,
    "folder": "sakuya waio",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "marugarete4w",
    "title": "\u30DE\u30EB\u30AC\u30EC\u30FC\u30C6",
    "img": "127.jpg",
    "brand": "NATIVE",
    "featured": false,
    "folder": "marugarete4w",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "youseiqueen",
    "title": "Dai-Yu \u30C0\u30A4\u30FB\u30E6\u30FC (Native)",
    "img": "87.jpg",
    "brand": "NATIVE",
    "featured": false,
    "folder": "youseiqueen",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "alicewaring",
    "title": "\u30A2\u30EA\u30B9 of \u54C1\u8A55\u6703",
    "img": "02.jpg",
    "brand": "NATIVE",
    "featured": false,
    "folder": "alicewaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "arikowaring",
    "title": "\u591C\u4F3D\u306E\u56FD\u306E\u4E9E\u7483\u5B50",
    "img": "91.jpg",
    "brand": "NATIVE",
    "featured": false,
    "folder": "arikowaring",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Ahri",
    "title": "Myethos-\u82F1\u96C4\u806F\u76DF \u9748\u9B42\u84EE\u83EF \u963F\u7483",
    "img": "152.jpg",
    "brand": "MYETHOS",
    "featured": false,
    "folder": "Ahri",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "AZD",
    "title": "A-Z:[D]",
    "img": "102.jpg",
    "brand": "MYETHOS",
    "featured": false,
    "folder": "AZD",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "hakuchou1",
    "title": "\u30C9\u30EA\u30FC\u30E0\u30C6\u30C3\u30AF \u767D\u9CE5\u306E\u5973\u306E\u5B50",
    "img": "100.jpg",
    "brand": "WAVE",
    "featured": false,
    "folder": "hakuchou1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "allsunday",
    "title": "Playback Memories\u201D \u30DF\u30B9\u30FB\u30AA\u30FC\u30EB\u30B5\u30F3\u30C7\u30FC",
    "img": "151.jpg",
    "brand": "MEGAHOUSE",
    "featured": false,
    "folder": "allsunday",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "habbkoku",
    "title": "\u30EF\u30F3\u30D4\u30FC\u30B9 \u30DC\u30A2\u30FB\u30CF\u30F3\u30B3\u30C3\u30AF Ver.BB",
    "img": "145.jpg",
    "brand": "MEGAHOUSE",
    "featured": false,
    "folder": "habbkoku",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "makima",
    "title": "BiCute Bunnies Figure \u30C1\u30A7\u30F3\u30BD\u30FC\u30DE\u30F3 \u30FC\u30DE\u30AD\u30DE\u30FC",
    "img": "154.jpg",
    "brand": "FURYU",
    "featured": false,
    "folder": "makima",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "pawa",
    "title": "BiCute Bunnies Figure \u30C1\u30A7\u30F3\u30BD\u30FC\u30DE\u30F3 \u30FC\u30D1\u30EF\u30FC\u30FC",
    "img": "153.jpg",
    "brand": "FURYU",
    "featured": false,
    "folder": "pawa",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "shutenzom1",
    "title": "\u30A2\u30B5\u30B7\u30F3\uFF0F\u9152\u5451\u7AE5\u5B50 \u82F1\u970A\u796D\u88DDVer.",
    "img": "116.jpg",
    "brand": "QUESQ",
    "featured": false,
    "folder": "shutenzom1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "UCINANA",
    "title": "ToLOVE\u308B\uFF0D\u3068\u3089\u3076\u308B\uFF0D\u30C0\u30FC\u30AF\u30CD\u30B9 \u30CA\u30CA\u30FB\u30A2\u30B9\u30BF\u30FB\u30C7\u30D3\u30EB\u30FC\u30AF \u30C0\u30FC\u30AF\u30CD\u30B9",
    "img": "101.jpg",
    "brand": "UCI",
    "featured": false,
    "folder": "UCINANA",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Astolfo",
    "title": "\u30B8\u30E3\u30F3\u30CC\u30FB\u30C0\u30EB\u30AF\uFF06\u30A2\u30B9\u30C8\u30EB\u30D5\u30A9 TYPE-MOON Racing ver.",
    "img": "98.jpg",
    "brand": "PLUSONE",
    "featured": false,
    "folder": "Astolfo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "mikusakura",
    "title": "\u6AFB\u672A\u4F86\uFF5E\u685C\u5996\u7CBEver",
    "img": "95.jpg",
    "brand": "SPIRITALE",
    "featured": false,
    "folder": "mikusakura",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "amilia_black",
    "title": "\u30A8\u30DF\u30EA\u30A2 -Crystal Dress Ver-",
    "img": "12.jpg",
    "brand": "ESTREAM",
    "featured": false,
    "folder": "amilia black",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "rinsia",
    "title": "\u7B2C3\u6751\u4EBA \u30EA\u30F3\u30B7\u30A2",
    "img": "18.jpg",
    "brand": "VERTEX",
    "featured": false,
    "folder": "rinsia",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Albedo",
    "title": "\u30AA\u30FC\u30D0\u30FC\u30ED\u30FC\u30C9 \u30A2\u30EB\u30D9\u30C9",
    "img": "67.jpg",
    "brand": "FNEX",
    "featured": false,
    "folder": "Albedo",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_alter_kimono",
    "title": "\u30BB\u30A4\u30D0\u30FC\u30AA\u30EB\u30BF \u7740\u7269Ver.",
    "img": "11.jpg",
    "brand": "KADOKAWA",
    "featured": false,
    "folder": "saber alter kimono",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "saber_haregi",
    "title": "saber \u6674\u308C\u7740",
    "img": "23.jpg",
    "brand": "ANIPLEX",
    "featured": false,
    "folder": "saber haregi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sie1",
    "title": "\u7F8E\u54B2\u8A69\u7D75 \u300C\u590F\u8349\u300D",
    "img": "108.jpg",
    "brand": "DAIKI",
    "featured": false,
    "folder": "sie1",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "kurumi",
    "title": "\u30C7\u30FC\u30C8\u30FB\u30A2\u30FB\u30E9\u30A4\u30D6\u2161\u300C\u6642\u5D0E \u72C2\u4E09\u300D",
    "img": "09.jpg",
    "brand": "BROCCOLI",
    "featured": false,
    "folder": "kurumi",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "arisa",
    "title": "\u30A2\u30EA\u30B5\u30FB\u30A4\u30EA\u30FC\u30CB\u30C1\u30CA\u30FB\u30A2\u30DF\u30A8\u30FC\u30E9",
    "img": "47.jpg",
    "brand": "PLUM",
    "featured": false,
    "folder": "arisa",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sakuya_teacher",
    "title": "\u30B5\u30AF\u30E4 -\u5973\u6559\u5E2BVer.-",
    "img": "59.jpg",
    "brand": "FLARE",
    "featured": false,
    "folder": "sakuya teacher",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "nejire",
    "title": "\u6CE2\u52D5\u306D\u3058\u308C \u30D2\u30FC\u30ED\u30FC\u30B9\u30FC\u30C4",
    "img": "148.jpg",
    "brand": "BELLFINE",
    "featured": false,
    "folder": "nejire",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "sigure",
    "title": "\u6642\u96E8\u7FBD\u8863 \u3057\u3050\u308C\u3046\u3044",
    "img": "141.jpg",
    "brand": "POP",
    "featured": false,
    "folder": "sigure",
    "totalFrames": 36,
    "customUrl": "",
    "reviewLink": "",
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "Hancock",
    "title": "Maximum \u6CE2\u96C5\u00B7\u6F22\u8003\u514B",
    "img": "144.jpg",
    "brand": "FNEX",
    "featured": false,
    "folder": "Hancock",
    "totalFrames": 36,
    "customUrl": null,
    "reviewLink": null,
    "credit": null,
    "is18Plus": false,
    "modes": null
  },
  {
    "id": "15th",
    "title": "Lemoe Vtuber \u7015\u81E8\u7D55\u7A2E\u5718 No.Fifteen \u5341\u4E94\u865F",
    "img": "155.jpg",
    "brand": "LEMOE",
    "featured": false,
    "folder": "15th_up",
    "totalFrames": 33,
    "customUrl": "",
    "reviewLink": "",
    "credit": "\u7531\u5DF4\u54C8\u7DB2\u53CB \u003Cspan class=\u0027text-violet-400\u0027\u003E998\u003C/span\u003E \u63D0\u4F9B",
    "is18Plus": false,
    "modes": [
      {
        "name": "\u901A\u5E38\u89D2\u5EA6",
        "folder": "15th",
        "totalFrames": 33,
        "is18Plus": false
      },
      {
        "name": "\u4F4E\u89D2\u5EA6\u4EF0\u8996",
        "folder": "15th",
        "totalFrames": 33,
        "is18Plus": false
      }
    ]
  },
  {
    "id": "miraboreasu1",
    "title": "\u9ED1\u9F8D - \u30DF\u30E9\u30DC\u30EC\u30A2\u30B9",
    "img": "109.jpg",
    "brand": "CBF",
    "featured": false,
    "folder": "miraboreasu1",
    "totalFrames": 36,
    "customUrl": "",
    "reviewLink": "https://\u4F60\u7684\u958B\u7BB1\u6587\u7DB2\u5740.com",
    "credit": "\u7531\u5DF4\u54C8\u7DB2\u53CB \u003Cspan class=\u0027text-red-400\u0027\u003E\u963F\u5B5F\u003C/span\u003E \u63D0\u4F9B",
    "is18Plus": false,
    "modes": [
      {
        "name": "\u5168\u5F69",
        "folder": "miraboreasu1",
        "totalFrames": 36,
        "is18Plus": false
      },
      {
        "name": "\u534A\u5F69",
        "folder": "miraboreasu2",
        "totalFrames": 36,
        "is18Plus": false
      },
      {
        "name": "77",
        "folder": "miraboreasu3",
        "totalFrames": 36,
        "is18Plus": false
      },
      {
        "name": "88",
        "folder": "miraboreasu4",
        "totalFrames": 36,
        "is18Plus": true
      }
    ]
  },
  {
    "id": "Xayah",
    "title": "\u82F1\u96C4\u806F\u76DF \u524E\u96C5",
    "img": "150.jpg",
    "brand": "HOBBYMAX",
    "featured": false,
    "folder": "Xayah",
    "totalFrames": 36,
    "customUrl": "http:\\\\google.com",
    "reviewLink": "",
    "credit": "\u7531\u5DF4\u54C8\u7DB2\u53CB \u003Cspan class=\u0027text-blue-400\u0027\u003E789777\u003C/span\u003E \u63D0\u4F9B",
    "is18Plus": false,
    "modes": null
  }
];